import { create } from 'zustand'
import { persist } from 'zustand/middleware'

const T = {
  en: {
    // Nav
    home: 'Home', games: 'Games', discover: 'Discover', friends: 'Friends',
    teams: 'Teams', tournaments: 'Tournaments', messages: 'Messages',
    view_profile: 'View Profile', edit_profile: 'Edit Profile', sign_out: 'Sign Out',
    log_in: 'Log In', sign_up: 'Sign Up',
    // Dashboard
    good_morning: 'Good morning', good_afternoon: 'Good afternoon', good_evening: 'Good evening',
    active_queues: 'Active Queues', recent_messages: 'Recent Messages', my_teams: 'My Teams',
    quick_join: 'Quick Join', team_invites: 'Team Invites', upcoming_tournaments: 'Tournaments',
    not_in_queues: 'Not in any queues', find_game: 'Find a game →',
    no_conversations: 'No conversations yet', no_teams: 'Not on any teams yet',
    create_one: 'Create one →', all_games: 'All games',
    queues: 'Queues', chats: 'Chats', events: 'Events',
    browse: 'Browse', all: 'All', view: 'View', leave: 'Leave',
    accept: 'Accept', decline: 'Decline',
    invited_you_to: 'invited you to',
    // Common
    save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', create: 'Create',
    loading: 'Loading...', open: 'Open', live: 'Live', add: 'Add', remove: 'Remove',
    back: 'Back',
    // Tournament list
    create_tournament: 'Create Tournament', tournament_name: 'Tournament Name',
    no_tournaments: 'No tournaments found',
    be_first_organize: 'Be the first to organize one!',
    registered_short: 'registered',
    compete_best: 'Compete and prove you\'re the best',
    // Tournament detail
    back_to_tournaments: 'Back to Tournaments',
    about: 'About',
    type: 'Type',
    team_type: 'Team',
    solo_type: 'Solo',
    min_team_size_stat: 'Min. team size',
    members_label: 'members',
    no_participants: 'No participants yet',
    bracket_not_generated: 'Bracket not generated yet',
    no_rules_specified: 'No rules specified',
    report_results: 'Report Match Results',
    select_team: 'Select team',
    create_team_to_join: 'Create a team to join',
    registered_badge: 'Registered',
    edit_tournament: 'Edit Tournament',
    start_tournament: 'Start',
    cancel_tournament_btn: 'Cancel',
    unregister: 'Unregister',
    submit_result: 'Submit Result',
    overview_tab: 'overview',
    participants_tab: 'participants',
    bracket_tab: 'bracket',
    rules_tab: 'rules',
    // Tournament form
    game: 'Game', any_game: 'Any game', participants: 'Participants',
    teams_label: 'Teams', solo_players: 'Solo players',
    min_members: 'Min. team members required', min_members_hint: '(to register)',
    format: 'Format', max_participants: 'Max Participants',
    single_elim: 'Single Elimination', double_elim: 'Double Elimination', round_robin: 'Round Robin',
    start_datetime: 'Start Date & Time', prize: 'Prize / Reward', prize_hint: '(optional)',
    description: 'Description', rules: 'Rules',
    describe_tournament: 'Describe your tournament...', enter_rules: 'Enter tournament rules...',
    tournament_image: 'Tournament Image', tournament_banner: 'Tournament Banner',
    click_to_upload_banner: 'Click to upload banner',
    square_image_hint: 'Square image used as the tournament icon in listings.',
    thumbnail: 'thumbnail',
    remove_image: 'Remove image',
    update_tournament: 'Update Tournament',
    // Edit Profile
    appearance: 'Appearance', click_to_change: 'Click banner or avatar to change · click',
    to_remove: 'to remove',
    basic_info: 'Basic Info', username: 'Username', display_name: 'Display Name',
    age: 'Age', country: 'Country', bio: 'Bio', social_links: 'Social Links',
    my_games: 'My Games', add_game: 'Add Game', main_game: 'Main game',
    save_profile: 'Save Profile', danger_zone: 'Danger Zone',
    delete_account: 'Delete Account',
    no_games_added: 'No games added yet. Add your favorite games!',
    select_game: 'Select game...',
    select_rank: 'Select rank...',
    select_role: 'Select role...',
    delete_account_desc: 'Permanently delete your account and all your data. This cannot be undone.',
    delete_my_account_btn: 'Delete my account',
    // Auth
    welcome_back: 'Welcome back', create_account: 'Create your account',
    email: 'Email', password: 'Password', username_label: 'Username',
    no_account: "Don't have an account?", have_account: 'Already have an account?',
    logging_in_text: 'Logging in...',
    creating_account_text: 'Creating account...',
    sign_up_free: 'Sign up free',
    agree_terms: 'By signing up you agree to our Terms of Service and Privacy Policy',
    only_letters: 'Only letters, numbers, and underscores',
    confirm_password: 'Confirm Password',
    repeat_password: 'Repeat your password',
    min_chars: 'Min. 6 characters',
    log_in_to_account: 'Log in to your GameMatch account',
    join_community: 'Join the GameMatch community',
  },
  es: {
    // Nav
    home: 'Inicio', games: 'Juegos', discover: 'Descubrir', friends: 'Amigos',
    teams: 'Equipos', tournaments: 'Torneos', messages: 'Mensajes',
    view_profile: 'Ver Perfil', edit_profile: 'Editar Perfil', sign_out: 'Cerrar Sesión',
    log_in: 'Iniciar Sesión', sign_up: 'Registrarse',
    // Dashboard
    good_morning: 'Buenos días', good_afternoon: 'Buenas tardes', good_evening: 'Buenas noches',
    active_queues: 'Colas Activas', recent_messages: 'Mensajes Recientes', my_teams: 'Mis Equipos',
    quick_join: 'Unirse Rápido', team_invites: 'Invitaciones de Equipo', upcoming_tournaments: 'Torneos',
    not_in_queues: 'No estás en ninguna cola', find_game: 'Buscar partida →',
    no_conversations: 'Sin conversaciones', no_teams: 'No estás en ningún equipo',
    create_one: 'Crear uno →', all_games: 'Todos los juegos',
    queues: 'Colas', chats: 'Chats', events: 'Eventos',
    browse: 'Ver', all: 'Todos', view: 'Ver', leave: 'Salir',
    accept: 'Aceptar', decline: 'Rechazar',
    invited_you_to: 'te invitó a',
    // Common
    save: 'Guardar', cancel: 'Cancelar', edit: 'Editar', delete: 'Eliminar', create: 'Crear',
    loading: 'Cargando...', open: 'Abierto', live: 'En vivo', add: 'Agregar', remove: 'Quitar',
    back: 'Atrás',
    // Tournament list
    create_tournament: 'Crear Torneo', tournament_name: 'Nombre del Torneo',
    no_tournaments: 'No se encontraron torneos',
    be_first_organize: '¡Sé el primero en organizar uno!',
    registered_short: 'registrados',
    compete_best: 'Compite y demuestra que sos el mejor',
    // Tournament detail
    back_to_tournaments: 'Volver a Torneos',
    about: 'Sobre',
    type: 'Tipo',
    team_type: 'Equipo',
    solo_type: 'Solo',
    min_team_size_stat: 'Tamaño mín. de equipo',
    members_label: 'miembros',
    no_participants: 'Sin participantes todavía',
    bracket_not_generated: 'Bracket no generado todavía',
    no_rules_specified: 'Sin reglas especificadas',
    report_results: 'Reportar Resultados',
    select_team: 'Seleccionar equipo',
    create_team_to_join: 'Crear un equipo para unirse',
    registered_badge: 'Registrado',
    edit_tournament: 'Editar Torneo',
    start_tournament: 'Iniciar',
    cancel_tournament_btn: 'Cancelar',
    unregister: 'Desregistrarse',
    submit_result: 'Enviar Resultado',
    overview_tab: 'descripción',
    participants_tab: 'participantes',
    bracket_tab: 'bracket',
    rules_tab: 'reglas',
    // Tournament form
    game: 'Juego', any_game: 'Cualquier juego', participants: 'Participantes',
    teams_label: 'Equipos', solo_players: 'Jugadores solos',
    min_members: 'Mín. miembros requeridos', min_members_hint: '(para registrarse)',
    format: 'Formato', max_participants: 'Máx. Participantes',
    single_elim: 'Eliminación Simple', double_elim: 'Doble Eliminación', round_robin: 'Round Robin',
    start_datetime: 'Fecha y Hora de Inicio', prize: 'Premio / Recompensa', prize_hint: '(opcional)',
    description: 'Descripción', rules: 'Reglas',
    describe_tournament: 'Describe tu torneo...', enter_rules: 'Escribe las reglas del torneo...',
    tournament_image: 'Imagen del Torneo', tournament_banner: 'Banner del Torneo',
    click_to_upload_banner: 'Clic para subir banner',
    square_image_hint: 'Imagen cuadrada usada como ícono en los listados.',
    thumbnail: 'miniatura',
    remove_image: 'Quitar imagen',
    update_tournament: 'Actualizar Torneo',
    // Edit Profile
    appearance: 'Apariencia', click_to_change: 'Clic en banner o avatar para cambiar · clic en',
    to_remove: 'para eliminar',
    basic_info: 'Info Básica', username: 'Usuario', display_name: 'Nombre',
    age: 'Edad', country: 'País', bio: 'Bio', social_links: 'Redes Sociales',
    my_games: 'Mis Juegos', add_game: 'Agregar Juego', main_game: 'Principal',
    save_profile: 'Guardar Perfil', danger_zone: 'Zona de Peligro',
    delete_account: 'Eliminar Cuenta',
    no_games_added: 'Sin juegos. ¡Agrega tus favoritos!',
    select_game: 'Seleccionar juego...',
    select_rank: 'Seleccionar rango...',
    select_role: 'Seleccionar rol...',
    delete_account_desc: 'Eliminar permanentemente tu cuenta y todos tus datos. Esto no se puede deshacer.',
    delete_my_account_btn: 'Eliminar mi cuenta',
    // Auth
    welcome_back: 'Bienvenido de vuelta', create_account: 'Crea tu cuenta',
    email: 'Correo', password: 'Contraseña', username_label: 'Usuario',
    no_account: '¿No tenés cuenta?', have_account: '¿Ya tenés cuenta?',
    logging_in_text: 'Iniciando sesión...',
    creating_account_text: 'Creando cuenta...',
    sign_up_free: 'Registrarse gratis',
    agree_terms: 'Al registrarte aceptás nuestros Términos y Política de Privacidad',
    only_letters: 'Solo letras, números y guiones bajos',
    confirm_password: 'Confirmar Contraseña',
    repeat_password: 'Repetí tu contraseña',
    min_chars: 'Mín. 6 caracteres',
    log_in_to_account: 'Iniciá sesión en tu cuenta',
    join_community: 'Unite a la comunidad',
  },
  pt: {
    // Nav
    home: 'Início', games: 'Jogos', discover: 'Descobrir', friends: 'Amigos',
    teams: 'Times', tournaments: 'Torneios', messages: 'Mensagens',
    view_profile: 'Ver Perfil', edit_profile: 'Editar Perfil', sign_out: 'Sair',
    log_in: 'Entrar', sign_up: 'Cadastrar',
    // Dashboard
    good_morning: 'Bom dia', good_afternoon: 'Boa tarde', good_evening: 'Boa noite',
    active_queues: 'Filas Ativas', recent_messages: 'Mensagens Recentes', my_teams: 'Meus Times',
    quick_join: 'Entrar Rápido', team_invites: 'Convites de Time', upcoming_tournaments: 'Torneios',
    not_in_queues: 'Você não está em nenhuma fila', find_game: 'Buscar partida →',
    no_conversations: 'Sem conversas ainda', no_teams: 'Você não está em nenhum time',
    create_one: 'Criar um →', all_games: 'Todos os jogos',
    queues: 'Filas', chats: 'Chats', events: 'Eventos',
    browse: 'Ver', all: 'Todos', view: 'Ver', leave: 'Sair',
    accept: 'Aceitar', decline: 'Recusar',
    invited_you_to: 'te convidou para',
    // Common
    save: 'Salvar', cancel: 'Cancelar', edit: 'Editar', delete: 'Excluir', create: 'Criar',
    loading: 'Carregando...', open: 'Aberto', live: 'Ao vivo', add: 'Adicionar', remove: 'Remover',
    back: 'Voltar',
    // Tournament list
    create_tournament: 'Criar Torneio', tournament_name: 'Nome do Torneio',
    no_tournaments: 'Nenhum torneio encontrado',
    be_first_organize: 'Seja o primeiro a organizar um!',
    registered_short: 'registrados',
    compete_best: 'Compita e prove que você é o melhor',
    // Tournament detail
    back_to_tournaments: 'Voltar aos Torneios',
    about: 'Sobre',
    type: 'Tipo',
    team_type: 'Time',
    solo_type: 'Solo',
    min_team_size_stat: 'Tamanho mín. de time',
    members_label: 'membros',
    no_participants: 'Sem participantes ainda',
    bracket_not_generated: 'Bracket não gerado ainda',
    no_rules_specified: 'Sem regras especificadas',
    report_results: 'Reportar Resultados',
    select_team: 'Selecionar time',
    create_team_to_join: 'Crie um time para participar',
    registered_badge: 'Registrado',
    edit_tournament: 'Editar Torneio',
    start_tournament: 'Iniciar',
    cancel_tournament_btn: 'Cancelar',
    unregister: 'Cancelar inscrição',
    submit_result: 'Enviar Resultado',
    overview_tab: 'visão geral',
    participants_tab: 'participantes',
    bracket_tab: 'bracket',
    rules_tab: 'regras',
    // Tournament form
    game: 'Jogo', any_game: 'Qualquer jogo', participants: 'Participantes',
    teams_label: 'Times', solo_players: 'Jogadores solo',
    min_members: 'Mín. membros necessários', min_members_hint: '(para se registrar)',
    format: 'Formato', max_participants: 'Máx. Participantes',
    single_elim: 'Eliminação Simples', double_elim: 'Dupla Eliminação', round_robin: 'Round Robin',
    start_datetime: 'Data e Hora de Início', prize: 'Prêmio / Recompensa', prize_hint: '(opcional)',
    description: 'Descrição', rules: 'Regras',
    describe_tournament: 'Descreva seu torneio...', enter_rules: 'Digite as regras do torneio...',
    tournament_image: 'Imagem do Torneio', tournament_banner: 'Banner do Torneio',
    click_to_upload_banner: 'Clique para enviar banner',
    square_image_hint: 'Imagem quadrada usada como ícone nas listagens.',
    thumbnail: 'miniatura',
    remove_image: 'Remover imagem',
    update_tournament: 'Atualizar Torneio',
    // Edit Profile
    appearance: 'Aparência', click_to_change: 'Clique no banner ou avatar para alterar · clique em',
    to_remove: 'para remover',
    basic_info: 'Info Básica', username: 'Usuário', display_name: 'Nome',
    age: 'Idade', country: 'País', bio: 'Bio', social_links: 'Redes Sociais',
    my_games: 'Meus Jogos', add_game: 'Adicionar Jogo', main_game: 'Principal',
    save_profile: 'Salvar Perfil', danger_zone: 'Zona de Perigo',
    delete_account: 'Excluir Conta',
    no_games_added: 'Sem jogos. Adicione seus favoritos!',
    select_game: 'Selecionar jogo...',
    select_rank: 'Selecionar rank...',
    select_role: 'Selecionar função...',
    delete_account_desc: 'Excluir permanentemente sua conta e todos os seus dados. Isso não pode ser desfeito.',
    delete_my_account_btn: 'Excluir minha conta',
    // Auth
    welcome_back: 'Bem-vindo de volta', create_account: 'Crie sua conta',
    email: 'E-mail', password: 'Senha', username_label: 'Usuário',
    no_account: 'Não tem conta?', have_account: 'Já tem conta?',
    logging_in_text: 'Entrando...',
    creating_account_text: 'Criando conta...',
    sign_up_free: 'Cadastrar grátis',
    agree_terms: 'Ao se cadastrar você concorda com nossos Termos e Política de Privacidade',
    only_letters: 'Apenas letras, números e underscores',
    confirm_password: 'Confirmar Senha',
    repeat_password: 'Repita sua senha',
    min_chars: 'Mín. 6 caracteres',
    log_in_to_account: 'Entre na sua conta',
    join_community: 'Entre na comunidade',
  },
}

export const useLangStore = create(
  persist(
    (set, get) => ({
      lang: 'es',
      setLang: (lang) => set({ lang }),
      t: (key) => T[get().lang]?.[key] ?? T.en[key] ?? key,
    }),
    { name: 'ruhq-lang' }
  )
)

// Hook for convenient use in components
export const useT = () => {
  const { lang, setLang, t } = useLangStore()
  return { t, lang, setLang }
}
