export const GAMES = [
  {
    id: 'valorant', name: 'Valorant', slug: 'valorant', genre: 'FPS', color: '#ff4655',
    cover_url: 'https://static-cdn.jtvnw.net/ttv-boxart/516575-285x380.jpg',
    rank_label: 'Rank', role_label: 'Agent Role',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Iron 1', value: 'iron1' }, { label: 'Iron 2', value: 'iron2' }, { label: 'Iron 3', value: 'iron3' },
      { label: 'Bronze 1', value: 'bronze1' }, { label: 'Bronze 2', value: 'bronze2' }, { label: 'Bronze 3', value: 'bronze3' },
      { label: 'Silver 1', value: 'silver1' }, { label: 'Silver 2', value: 'silver2' }, { label: 'Silver 3', value: 'silver3' },
      { label: 'Gold 1', value: 'gold1' }, { label: 'Gold 2', value: 'gold2' }, { label: 'Gold 3', value: 'gold3' },
      { label: 'Platinum 1', value: 'plat1' }, { label: 'Platinum 2', value: 'plat2' }, { label: 'Platinum 3', value: 'plat3' },
      { label: 'Diamond 1', value: 'diamond1' }, { label: 'Diamond 2', value: 'diamond2' }, { label: 'Diamond 3', value: 'diamond3' },
      { label: 'Ascendant 1', value: 'asc1' }, { label: 'Ascendant 2', value: 'asc2' }, { label: 'Ascendant 3', value: 'asc3' },
      { label: 'Immortal 1', value: 'immo1' }, { label: 'Immortal 2', value: 'immo2' }, { label: 'Immortal 3', value: 'immo3' },
      { label: 'Radiant', value: 'radiant' },
    ],
    roles: [
      { label: 'Duelist', value: 'duelist' },
      { label: 'Initiator', value: 'initiator' },
      { label: 'Controller', value: 'controller' },
      { label: 'Sentinel', value: 'sentinel' },
      { label: 'Flex (any)', value: 'flex' },
    ],
    looking_for_options: [
      { label: '+1 (duo)', value: 'duo' },
      { label: '+2 (trio)', value: 'trio' },
      { label: '+3 (4-stack)', value: 'stack4' },
      { label: 'Full 5-stack', value: 'full5' },
      { label: 'Scrim / 10-man', value: 'scrim' },
      { label: 'Coaching', value: 'coaching' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Need IGL, no smurfs, mic required...',
  },
  {
    id: 'cs2', name: 'Counter-Strike 2', slug: 'cs2', genre: 'FPS', color: '#de9b35',
    cover_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',
    rank_label: 'Rank', role_label: 'Role',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Silver I', value: 's1' }, { label: 'Silver II', value: 's2' }, { label: 'Silver III', value: 's3' },
      { label: 'Silver IV', value: 's4' }, { label: 'Silver Elite', value: 'se' }, { label: 'Silver Elite Master', value: 'sem' },
      { label: 'Gold Nova I', value: 'gn1' }, { label: 'Gold Nova II', value: 'gn2' }, { label: 'Gold Nova III', value: 'gn3' },
      { label: 'Gold Nova Master', value: 'gnm' },
      { label: 'Master Guardian I', value: 'mg1' }, { label: 'Master Guardian II', value: 'mg2' },
      { label: 'Master Guardian Elite', value: 'mge' },
      { label: 'Distinguished Master Guardian', value: 'dmg' },
      { label: 'Legendary Eagle', value: 'le' }, { label: 'Legendary Eagle Master', value: 'lem' },
      { label: 'Supreme Master First Class', value: 'smfc' },
      { label: 'Global Elite', value: 'ge' },
      { label: 'Premier: 5k-10k', value: 'pr_blue' },
      { label: 'Premier: 10k-15k', value: 'pr_teal' },
      { label: 'Premier: 15k-20k', value: 'pr_purple' },
      { label: 'Premier: 20k-25k', value: 'pr_pink' },
      { label: 'Premier: 25k+', value: 'pr_red' },
    ],
    roles: [
      { label: 'Entry Fragger', value: 'entry' },
      { label: 'AWPer', value: 'awper' },
      { label: 'IGL (Caller)', value: 'igl' },
      { label: 'Support / Utility', value: 'support' },
      { label: 'Lurker', value: 'lurker' },
      { label: 'Rifler / Flex', value: 'rifler' },
    ],
    looking_for_options: [
      { label: '+1 (duo)', value: 'duo' },
      { label: '+2 (trio)', value: 'trio' },
      { label: 'Full 5-stack', value: 'full5' },
      { label: 'Scrim / Practice', value: 'scrim' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Premier only, need AWPer, no rage quitters...',
  },
  {
    id: 'lol', name: 'League of Legends', slug: 'lol', genre: 'MOBA', color: '#c89b3c',
    cover_url: 'https://static-cdn.jtvnw.net/ttv-boxart/21779-285x380.jpg',
    rank_label: 'Rank', role_label: 'Lane / Role',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Iron', value: 'iron' }, { label: 'Bronze', value: 'bronze' }, { label: 'Silver', value: 'silver' },
      { label: 'Gold', value: 'gold' }, { label: 'Platinum', value: 'platinum' }, { label: 'Emerald', value: 'emerald' },
      { label: 'Diamond', value: 'diamond' }, { label: 'Master', value: 'master' },
      { label: 'Grandmaster', value: 'grandmaster' }, { label: 'Challenger', value: 'challenger' },
    ],
    roles: [
      { label: 'Top', value: 'top' },
      { label: 'Jungle', value: 'jungle' },
      { label: 'Mid', value: 'mid' },
      { label: 'Bot / ADC', value: 'adc' },
      { label: 'Support', value: 'support' },
      { label: 'Fill', value: 'fill' },
    ],
    looking_for_options: [
      { label: '+1 (duo queue)', value: 'duo' },
      { label: 'Flex 5-stack', value: 'flex5' },
      { label: 'Clash team', value: 'clash' },
      { label: 'Normal / fun games', value: 'normal' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Need jungle main, Clash team, voice chat required...',
  },
  {
    id: 'fortnite', name: 'Fortnite', slug: 'fortnite', genre: 'Battle Royale', color: '#00d4ff',
    cover_url: 'https://static-cdn.jtvnw.net/ttv-boxart/33214-285x380.jpg',
    rank_label: 'Ranked Tier', role_label: 'Mode',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Bronze', value: 'fn_bronze' }, { label: 'Silver', value: 'fn_silver' }, { label: 'Gold', value: 'fn_gold' },
      { label: 'Platinum', value: 'fn_plat' }, { label: 'Diamond', value: 'fn_diamond' },
      { label: 'Elite', value: 'fn_elite' }, { label: 'Champion', value: 'fn_champion' },
      { label: 'Unreal', value: 'fn_unreal' },
      { label: 'Unranked / Casual', value: 'fn_casual' },
    ],
    roles: [
      { label: 'Battle Royale (Build)', value: 'br' },
      { label: 'Zero Build', value: 'zerobuild' },
      { label: 'Competitive (FNCS)', value: 'competitive' },
      { label: 'Creative / Maps', value: 'creative' },
    ],
    looking_for_options: [
      { label: 'Duo', value: 'duo' },
      { label: 'Trio', value: 'trio' },
      { label: 'Squad (4)', value: 'squad' },
      { label: 'Competitive / Cash Cup', value: 'comp' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Zero Build only, FNCS practice, must build...',
  },
  {
    id: 'apex', name: 'Apex Legends', slug: 'apex', genre: 'Battle Royale', color: '#da3f24',
    cover_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg',
    rank_label: 'Rank', role_label: 'Legend Class',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Rookie', value: 'rookie' }, { label: 'Bronze', value: 'ap_bronze' }, { label: 'Silver', value: 'ap_silver' },
      { label: 'Gold', value: 'ap_gold' }, { label: 'Platinum', value: 'ap_plat' }, { label: 'Diamond', value: 'ap_diamond' },
      { label: 'Master', value: 'ap_master' }, { label: 'Apex Predator', value: 'predator' },
    ],
    roles: [
      { label: 'Assault (Bangalore, Ash, Fuse...)', value: 'assault' },
      { label: 'Skirmisher (Wraith, Pathfinder, Octane...)', value: 'skirmisher' },
      { label: 'Recon (Bloodhound, Crypto, Seer...)', value: 'recon' },
      { label: 'Support (Lifeline, Newcastle, Gibraltar...)', value: 'support' },
      { label: 'Controller (Caustic, Catalyst, Rampart...)', value: 'controller' },
      { label: 'IGL / Shot-caller', value: 'igl' },
      { label: 'Flex', value: 'flex' },
    ],
    looking_for_options: [
      { label: '+1 (duo)', value: 'duo' },
      { label: 'Full squad (trio)', value: 'trio' },
      { label: 'Ranked grind', value: 'ranked' },
      { label: 'Scrims', value: 'scrim' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Ranked grind, need IGL, mic required, no Caustic mains...',
  },
  {
    id: 'rocketleague', name: 'Rocket League', slug: 'rocketleague', genre: 'Sports', color: '#0085ff',
    cover_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg',
    rank_label: 'Rank', role_label: 'Preferred Mode',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Bronze', value: 'rl_bronze' }, { label: 'Silver', value: 'rl_silver' }, { label: 'Gold', value: 'rl_gold' },
      { label: 'Platinum', value: 'rl_plat' }, { label: 'Diamond', value: 'rl_diamond' },
      { label: 'Champion', value: 'champion' }, { label: 'Grand Champion', value: 'gc' },
      { label: 'Supersonic Legend', value: 'ssl' },
    ],
    roles: [
      { label: '1v1 (Duel)', value: '1v1' },
      { label: '2v2 (Doubles)', value: '2v2' },
      { label: '3v3 (Standard)', value: '3v3' },
      { label: 'Hoops', value: 'hoops' },
      { label: 'Dropshot', value: 'dropshot' },
      { label: 'Snow Day', value: 'snowday' },
    ],
    looking_for_options: [
      { label: 'Partner for 2v2', value: '2v2partner' },
      { label: '2 teammates for 3v3', value: '3v3team' },
      { label: 'Ranked grind', value: 'ranked' },
      { label: 'Freestyling / freeplay', value: 'freestyle' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: '3v3 only, consistent rotation, boost-aware...',
  },
  {
    id: 'minecraft', name: 'Minecraft', slug: 'minecraft', genre: 'Sandbox', color: '#5d8732',
    cover_url: 'https://static-cdn.jtvnw.net/ttv-boxart/27471-285x380.jpg',
    rank_label: 'Experience Level', role_label: 'Activity',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Beginner (new player)', value: 'mc_beginner' },
      { label: 'Casual', value: 'mc_casual' },
      { label: 'Intermediate', value: 'mc_inter' },
      { label: 'Experienced', value: 'mc_exp' },
      { label: 'Hardcore / Expert', value: 'mc_expert' },
    ],
    roles: [
      { label: 'Survival / SMP', value: 'smp' },
      { label: 'Hypixel BedWars', value: 'bedwars' },
      { label: 'Hypixel SkyWars', value: 'skywars' },
      { label: 'Hypixel SkyBlock', value: 'skyblock' },
      { label: 'Hypixel Pit / PvP', value: 'pvp' },
      { label: 'Creative / Building', value: 'creative' },
      { label: 'Modded (Forge / Fabric)', value: 'modded' },
      { label: 'Technical / Redstone', value: 'technical' },
      { label: 'Prison / Economy servers', value: 'prison' },
      { label: 'Mini-games (other)', value: 'minigames' },
    ],
    looking_for_options: [
      { label: 'Duo', value: 'duo' },
      { label: 'Small group (3-5)', value: 'group' },
      { label: 'SMP members', value: 'smp_members' },
      { label: 'BedWars team', value: 'bw_team' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Starting a new SMP, BedWars 4s team, Java only...',
  },
  {
    id: 'dota2', name: 'Dota 2', slug: 'dota2', genre: 'MOBA', color: '#cc3433',
    cover_url: 'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg',
    rank_label: 'Medal', role_label: 'Position',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Herald', value: 'herald' }, { label: 'Guardian', value: 'guardian' },
      { label: 'Crusader', value: 'crusader' }, { label: 'Archon', value: 'archon' },
      { label: 'Legend', value: 'legend' }, { label: 'Ancient', value: 'ancient' },
      { label: 'Divine', value: 'divine' }, { label: 'Immortal', value: 'immortal' },
    ],
    roles: [
      { label: 'Pos 1 - Hard Carry', value: 'carry' },
      { label: 'Pos 2 - Mid Lane', value: 'mid' },
      { label: 'Pos 3 - Offlane', value: 'offlane' },
      { label: 'Pos 4 - Soft Support', value: 'pos4' },
      { label: 'Pos 5 - Hard Support', value: 'pos5' },
      { label: 'Flex (any position)', value: 'flex' },
    ],
    looking_for_options: [
      { label: '+1 (duo queue)', value: 'duo' },
      { label: '+2 (trio)', value: 'trio' },
      { label: 'Full 5-stack', value: 'full5' },
      { label: 'Scrimmage', value: 'scrim' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Need carry and mid, no feeding, ranked only...',
  },
  {
    id: 'overwatch2', name: 'Overwatch 2', slug: 'overwatch2', genre: 'FPS', color: '#f99e1a',
    cover_url: 'https://static-cdn.jtvnw.net/ttv-boxart/515025-285x380.jpg',
    rank_label: 'Rank', role_label: 'Role',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Bronze', value: 'ow_bronze' }, { label: 'Silver', value: 'ow_silver' }, { label: 'Gold', value: 'ow_gold' },
      { label: 'Platinum', value: 'ow_plat' }, { label: 'Diamond', value: 'ow_diamond' },
      { label: 'Master', value: 'ow_master' }, { label: 'Grandmaster', value: 'ow_gm' },
      { label: 'Champion', value: 'ow_champion' },
    ],
    roles: [
      { label: 'Tank', value: 'tank' },
      { label: 'Damage (DPS)', value: 'dps' },
      { label: 'Support / Healer', value: 'support' },
      { label: 'Flex (any role)', value: 'flex' },
    ],
    looking_for_options: [
      { label: '+1 (duo)', value: 'duo' },
      { label: '+2 (trio)', value: 'trio' },
      { label: '+3 (4-stack)', value: 'stack4' },
      { label: 'Full 5-stack', value: 'full5' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Need main tank, mic required, no tilters...',
  },
  {
    id: 'r6siege', name: 'Rainbow Six Siege', slug: 'r6siege', genre: 'FPS', color: '#4a90d9',
    cover_url: 'https://staticctf.ubisoft.com/J3yJr34U2pZ2Ieem48Dwy9uqj5PNUDgE/1AFx5jyGBFNqsUpaMWaC3C/4a95a3484cdfb01cf80f13aba66e94f3/r6s-keyart-full.jpg',
    rank_label: 'Rank', role_label: 'Play Style',
    has_ranks: true, has_roles: true,
    ranks: [
      { label: 'Copper', value: 'copper' }, { label: 'Bronze', value: 'r6_bronze' },
      { label: 'Silver', value: 'r6_silver' }, { label: 'Gold', value: 'r6_gold' },
      { label: 'Platinum', value: 'r6_plat' }, { label: 'Emerald', value: 'r6_emerald' },
      { label: 'Diamond', value: 'r6_diamond' }, { label: 'Champions', value: 'champions' },
    ],
    roles: [
      { label: 'Hard Breach (Thermite, Hibana...)', value: 'hard_breach' },
      { label: 'Soft Breach / Flank (Ash, Sledge...)', value: 'soft_breach' },
      { label: 'Support / Intel (Lion, Zero...)', value: 'support_atk' },
      { label: 'Roamer (fast defender)', value: 'roamer' },
      { label: 'Anchor / Hold site (Echo, Maestro...)', value: 'anchor' },
      { label: 'IGL / Caller', value: 'igl' },
      { label: 'Flex (ATK & DEF)', value: 'flex' },
    ],
    looking_for_options: [
      { label: '+1 (duo)', value: 'duo' },
      { label: '+2 (trio)', value: 'trio' },
      { label: 'Full 5-stack', value: 'full5' },
      { label: 'Scrimmage / Ranked', value: 'scrim' },
      { label: 'Any', value: 'any' },
    ],
    note_placeholder: 'Need IGL, ranked only, mic required, no boosters...',
  },
]

export const GAME_BY_SLUG = Object.fromEntries(GAMES.map(g => [g.slug, g]))
export const GAME_BY_ID = Object.fromEntries(GAMES.map(g => [g.id, g]))

export const LOOKING_FOR_OPTIONS = [
  { label: 'Duo', value: 'duo' },
  { label: 'Trio', value: 'trio' },
  { label: 'Full Team (5)', value: 'full_team' },
  { label: 'Scrimmage', value: 'scrim' },
  { label: 'Any', value: 'any' },
]

export const RANK_COLORS = {
  bronze: '#ad7c3c', silver: '#9aa6b2', gold: '#f5c842', platinum: '#00e5cc',
  diamond: '#4fc3f7', master: '#9b3be8', grandmaster: '#e84057', challenger: '#e8c84a',
  immortal: '#e84057', radiant: '#fffbd1', champion: '#f5a623', gc: '#f5a623', ssl: '#00d4ff',
  predator: '#e84057', rookie: '#8b8b8b',
  herald: '#9d7c4a', guardian: '#ad7c3c', crusader: '#9aa6b2',
  archon: '#f5c842', legend: '#00e5cc', ancient: '#4fc3f7', divine: '#9b3be8',
  iron1: '#9d7c4a', iron2: '#9d7c4a', iron3: '#9d7c4a',
  bronze1: '#ad7c3c', bronze2: '#ad7c3c', bronze3: '#ad7c3c',
  silver1: '#9aa6b2', silver2: '#9aa6b2', silver3: '#9aa6b2',
  gold1: '#f5c842', gold2: '#f5c842', gold3: '#f5c842',
  plat1: '#00e5cc', plat2: '#00e5cc', plat3: '#00e5cc',
  diamond1: '#4fc3f7', diamond2: '#4fc3f7', diamond3: '#4fc3f7',
  asc1: '#3bdc76', asc2: '#3bdc76', asc3: '#3bdc76',
  immo1: '#e84057', immo2: '#e84057', immo3: '#e84057',
  pr_blue: '#4fc3f7', pr_teal: '#00e5cc', pr_purple: '#9b3be8', pr_pink: '#e84057', pr_red: '#ff4655',
  fn_bronze: '#ad7c3c', fn_silver: '#9aa6b2', fn_gold: '#f5c842', fn_plat: '#00e5cc',
  fn_diamond: '#4fc3f7', fn_elite: '#9b3be8', fn_champion: '#f5a623', fn_unreal: '#fffbd1', fn_casual: '#9aa6b2',
  ap_bronze: '#ad7c3c', ap_silver: '#9aa6b2', ap_gold: '#f5c842', ap_plat: '#00e5cc',
  ap_diamond: '#4fc3f7', ap_master: '#9b3be8',
  rl_bronze: '#ad7c3c', rl_silver: '#9aa6b2', rl_gold: '#f5c842', rl_plat: '#00e5cc', rl_diamond: '#4fc3f7',
  iron: '#9d7c4a', emerald: '#00b070',
  ow_bronze: '#ad7c3c', ow_silver: '#9aa6b2', ow_gold: '#f5c842', ow_plat: '#00e5cc',
  ow_diamond: '#4fc3f7', ow_master: '#9b3be8', ow_gm: '#e84057', ow_champion: '#fffbd1',
  copper: '#ad7c3c', r6_bronze: '#ad7c3c', r6_silver: '#9aa6b2', r6_gold: '#f5c842',
  r6_plat: '#00e5cc', r6_emerald: '#00b070', r6_diamond: '#4fc3f7', champions: '#fffbd1',
  mc_beginner: '#9aa6b2', mc_casual: '#5d8732', mc_inter: '#f5c842', mc_exp: '#00e5cc', mc_expert: '#e84057',
}
